sonar.organization=ages-v-stable
sonar.projectKey=ages-v-stable_frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.spec.tsx,src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,coverage/**
sonar.coverage.exclusions=src/**/*.spec.ts,src/**/*.spec.tsx,src/**/*.test.ts,src/**/*.test.tsx,src/main.tsx,src/setupTests.ts,src/vite-env.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
